---
- name: download latest exakat
  get_url: url=http://dist.exakat.io/versions/index.php?file=latest dest=/home/vagrant/exakat.phar
  tags:
    - exakat

- name: clean database
  shell: cd /home/vagrant/; php exakat.phar cleandb 
  tags:
    - exakat

- name: run doctor 
  shell: cd /home/vagrant/; php exakat.phar doctor
  tags:
    - exakat
